# Generated by Django 5.1 on 2024-10-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0002_foodentry_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
