# Generated by Django 5.1 on 2024-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0004_foodentry_carbs_foodentry_fat_foodentry_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
