# Generated by Django 5.1 on 2024-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0005_remove_foodentry_quantity_foodentry_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='fat',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fats',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(),
        ),
    ]
