# Generated by Django 5.1 on 2024-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0006_remove_foodentry_fat_foodentry_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
