# Generated by Django 5.1 on 2024-10-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0007_alter_userdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
                ('food_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_1.foodentry')),
            ],
        ),
    ]
