# Generated by Django 5.1 on 2024-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0008_dayplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='meal_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['user_name', 'date'], name='part_1_dayp_user_na_ce27ab_idx'),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['date', 'meal_type'], name='part_1_dayp_date_aef0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['user_name', 'meal_type'], name='part_1_food_user_na_d74034_idx'),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['food_name', 'calories'], name='part_1_food_food_na_5968c2_idx'),
        ),
    ]
